FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y dovecot-core && rm -rf /var/lib/apt/lists/*
COPY usr/local/bin /usr/local/bin
RUN chmod +x /usr/local/bin/activitypub_*.py
CMD ["python3", "/usr/local/bin/activitypub_lmtp_server.py"]
